
const SA=firebase.auth();let SD=[],SS=null;
function sn(v){return String(v||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ')}
async function sh(v){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(sn(v)));return Array.from(new Uint8Array(d)).map(x=>x.toString(16).padStart(2,'0')).join('')}
function se(k){return 'student.'+k+'@practicas-profesionales-us21.firebaseapp.com'}
function sc(){const a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',b=new Uint8Array(8);crypto.getRandomValues(b);return Array.from(b).map(x=>a[x%a.length]).join('')}
function sf(x){return ((x.name||'')+' '+(x.surname||'')).trim()}
function sl(m){
 const o=SD.filter(x=>x.active!==false).map(x=>'<option value="'+esc(sf(x))+'"></option>').join('');
 const tabs='<div class="tabs"><button class="btn tab '+(m==='login'?'active':'')+'" onclick="sl(\'login\')">Iniciar sesión</button><button class="btn tab '+(m==='register'?'active':'')+'" onclick="sl(\'register\')">Registrarse</button><button class="btn tab '+(m==='tutor'?'active':'')+'" onclick="sl(\'tutor\')">Tutor</button></div>';
 let body='';
 if(m==='register')body='<form class="form" onsubmit="sr(event)"><div class="row"><div class="field"><label>Nombre</label><input id="rn" required></div><div class="field"><label>Apellido</label><input id="rs" required></div></div><div class="field"><label>Carrera</label><input id="rc" required></div><button class="btn btn-primary">Registrarme</button></form>';
 else if(m==='tutor')body='<form class="form" onsubmit="st(event)"><div class="field"><label>Email del tutor</label><input id="te" type="email" required></div><div class="field"><label>Contraseña</label><input id="tp" type="password" required></div><button class="btn btn-primary">Ingresar al panel de tutor</button></form>';
 else body='<form class="form" onsubmit="si(event)"><div class="field"><label>Nombre</label><input id="ln" list="sd" oninput="sa()" required><datalist id="sd">'+o+'</datalist></div><div class="row"><div class="field"><label>Apellido</label><input id="ls" required></div><div class="field"><label>Carrera</label><input id="lc" required></div></div><div class="field"><label>Clave personal</label><input id="lk" type="password" minlength="8" maxlength="8" required></div><button class="btn btn-primary">Iniciar sesión</button></form>';
 document.getElementById('app').innerHTML='<div class="shell"><div class="login panel"><div class="eyebrow">GESTIÓN ACADÉMICA EN LA NUBE</div><h2>PRÁCTICAS PROFESIONALES</h2><div class="subtitle">Acceso seguro y sincronizado.</div>'+tabs+body+'</div></div>';
}
function sa(){const v=document.getElementById('ln').value,x=SD.find(s=>s.active!==false&&sn(sf(s))===sn(v));if(x){document.getElementById('ls').value=x.surname||'';document.getElementById('lc').value=x.career||''}}
async function sr(e){e.preventDefault();try{const n=rn.value.trim(),s=rs.value.trim(),c=rc.value.trim(),k=await sh(n+'|'+s+'|'+c),id='stu-'+k.slice(0,20),code=sc(),u=await SA.createUserWithEmailAndPassword(se(k),code);await firestore.collection('student_profiles').doc(u.user.uid).set({uid:u.user.uid,studentId:id,name:n,surname:s,career:c,active:true,createdAt:new Date().toISOString()});await firestore.collection('student_directory').doc(k).set({studentId:id,name:n,surname:s,career:c,active:true},{merge:true});SS={role:'student',uid:u.user.uid,studentId:id};session={role:'student',studentId:id,tab:'home',uid:u.user.uid};alert('Registro completado. Tu clave personal es: '+code);renderStudent()}catch(x){alert('No se pudo registrar: '+x.message)}}
async function si(e){e.preventDefault();try{const k=await sh(ln.value.trim()+'|'+ls.value.trim()+'|'+lc.value.trim()),u=await SA.signInWithEmailAndPassword(se(k),lk.value.trim()),p=await firestore.collection('student_profiles').doc(u.user.uid).get();if(!p.exists||p.data().active===false)throw new Error('Cuenta no habilitada.');const x=p.data();SS={role:'student',uid:u.user.uid,studentId:String(x.studentId)};session={role:'student',studentId:String(x.studentId),tab:'home',uid:u.user.uid};renderStudent()}catch(x){alert('No se pudo iniciar sesión: '+x.message)}}
async function st(e){e.preventDefault();try{const u=await SA.signInWithEmailAndPassword(te.value.trim(),tp.value),t=await firestore.collection('tutores').doc(u.user.uid).get();if(!t.exists||t.data().active===false)throw new Error('Cuenta no autorizada como tutor.');session={role:'tutor',tutor:t.data().name||u.user.email,tab:'dashboard',uid:u.user.uid};renderTutor()}catch(x){alert('No se pudo ingresar como tutor: '+x.message)}}
async function so(){SS=null;session=null;await SA.signOut();sl('login')}
firestore.collection('student_directory').onSnapshot(s=>{SD=s.docs.map(d=>Object.assign({id:d.id},d.data()));if(!SS)sl('login')});
sl('login');
